export const relayEvents = [
  "register",
  "registered",
  "message",
  "group:create",
  "group:join",
  "group:leave",
  "group:message",
  "typing",
  "user:online",
  "user:lookup",
  "user:lookup:result",
  "file:share",
  "file:incoming",
  "matching:start",
  "matching:cancel",
  "matching:accept",
  "matching:decline",
  "matching:message",
  "matching:end_session",
  "matching:file_share",
  "webrtc:offer",
  "webrtc:answer",
  "webrtc:ice",
  "p2p:file-offer",
  "p2p:file-incoming",
] as const;

export type RelayEvent = (typeof relayEvents)[number];
